### ISSUE TITLE
Unit vs Instrumentation tests

### ISSUE THREAD

**Issue by sgrif** [scala-android/sbt-android#108]
Is there an example anywhere of an application that has both unit tests that can be run with the plain `test` command, as well as instrumentation tests that run on the device? From what I can tell, the plugin currently expects everything to be placed in the `src/androidTest` directory, which prevents the `android:test` command from running at all, since including scalatest and mockito (and potentially the scala language at all?) causes an error about too many methods being referenced during dexing. Is there a way to separate these out? If not, is this something that could be remedied with a multi-project build? Is there an example of how to achieve this anywhere?

**Comment by sgrif** [comment]
I would like to re-iterate that claiming this is supported when there is not proper support for dependencies, which requires separating unit test dependencies from instrumentation test dependencies, and that neither one of them be included in debug or production builds.

**Comment by pfn** [comment]
`flavorOf` addresses this
