### ISSUE TITLE
AARs that are provided by test only dependencies are included when compiling the main application

### ISSUE THREAD

**Issue by sgrif** [scala-android/sbt-android#110]
Adding `"com.jakewharton.espresso" % "espresso" % "1.1-r3" % "test"` to our `libraryDependencies` caused code to be added to our main compile stage, even though the library was only added for tests. The only output that I could find to indicate why was that it was unpacking AARs from that library. I have `debugIncludesTest in Android := false`

**Comment by sgrif** [comment]
That setting has no effect, and a dependency that is qualified as only for tests is still included in the final APK if it provides an AAR file.

**Comment by pfn** [comment]
try taking less than 6 months to respond to an issue you open.
