### ISSUE TITLE
Problem with proguard cache?

### ISSUE THREAD

**Issue by migo** [scala-android/sbt-android#19]
It seems to me that the proguard cache is not used correctly in the plug-in.

If I generate my app with clean and then android:install, then everything works ok. Proguard is executed, the app is installed and runs without problems.

However, if I leave out the clean and I don't change any code (e.g. I just change something in xml files), then proguard is not executed again, but the dex file is regenerated nevertheless without using proguard and apparently without including the scala library.

This is the output:

```
[info] [debug] cache hit, skipping proguard!
[info] [debug] Forcing clean dex
[info] Generating classes.dex
[info] Packaged: guidemate-debug-unaligned.apk (2,64MB)
[info] Debug package does not need signing: guidemate-debug-unaligned.apk
[info] zipaligned: guidemate-debug.apk
[info] Installing...
[info] [guidemate-debug.apk] Install finished: 2,64MB in 17,17s. 157,37KB/s
```

In tasks.scala (proguardTaskDef), there is this part:

```
if (inputs.proguardCache exists (_.exists)) {
    s.log.info("[debug] cache hit, skipping proguard!")
    None
}  
```

I think the problem could be that None is returned here instead of the cached jar file.

**Comment by veegee** [comment]
I'm also getting this issue, or something similar due to the fact that the cache is being "hit". Is there any way to disable the proguard cache?

**Comment by pfn** [comment]
proguardCache in Android := Nil

--

**Comment by veegee** [comment]
Thanks. I've been experiencing a lot of issues and decided to look through the bug tracker. A lot of these are easy fixes that can save everyone hours/days of time if there was some kind of documentation available. Perhaps a wiki is appropriate; it's something that can be contributed to easily.

**Comment by liskin** [comment]
I just hit this as well using little more than hello-scaloid-sbt. Is everyone supposed to set proguardCache in Android := Nil these days or have I done something wrong?

**Comment by pfn** [comment]
there are no known issues with proguard cache. scaloid is not a good example of how to setup sbt

**Comment by liskin** [comment]
Would you mind elaborating on that a bit? What do they do wrong and what should I do to setup sbt correctly?

**Comment by pfn** [comment]
use gitter, you haven't asked any problem yet.

**Comment by liskin** [comment]
For anyone else reading this and not having time to dig through gitter archives: the issue I (and possibly @veegee) had was a different one and turned out to need this fix: https://github.com/pfn/android-sdk-plugin/commit/11e1b52dc9dfa39b1a7afd344eb02cf20c99c2d2.
