### ISSUE TITLE
1.6.0 tries to TR .dotfiles in drawable directories

### ISSUE THREAD

**Issue by mikelpr** [scala-android/sbt-android#254]
I had a .directory file left by Dolphin (KDE) in drawable-hdpi and it caused this to appear:
`[error] /home/mikel/dev/Android/hivee/target/android/generated/source/io/hivee/android/TR.scala:230: illegal start of simple pattern
[error]     final val  = TypedRes[TypedResource.ResDrawable](R.drawable.)
[error]                ^`

thankfully the file tree in intellij was in a position I could spot it quickly and assumed the error was due to it, but it spooked me for a moment as it doesn't point in any way to the file that caused the error

**Comment by pfn** [comment]
thanks for the report
