### ISSUE TITLE
Dealing with deprecations in TR

### ISSUE THREAD

**Issue by MateuszKubuszok** [scala-android/sbt-android#261]
When I build my project with TR enabled I got warnings like this one:
```
[warn] .../TR.scala:1587: method getColor in class Resources is deprecated: see corresponding Javadoc for more information.
[warn]         c.getResources.getColor(resid)
[warn]              
```
(same for `c.getResources.getDrawable(resid)`).

I would be happy to build with `-Xfatal-warnings` and this is the last issue that separates me currently from warning-free build.

If there is no way of suppressing those, that I am unaware of, would it be a problem to add one?

**Comment by pfn** [comment]
deprecation warnings are impossible to suppress

**Comment by MateuszKubuszok** [comment]
Something like `c.getResources.getColor(resid, null)` wouldn't solve that?

**Comment by Taig** [comment]
@pfn Couldn't a Java-helper solve that? [Taig/Toolbelt](https://github.com/Taig/Toolbelt/blob/master/src/main/java/io/taig/android/compatibility/Resources.java#L14)

**Comment by pfn** [comment]
@MateuszKubuszok only if you want to crash at runtime

**Comment by pfn** [comment]
@Taig yes, deferring to a java helper would solve it, but then would have to add another file into the mix, yech

**Comment by dant3** [comment]
could deal with this in scala by making a forwarder workaround as in https://issues.scala-lang.org/browse/SI-7934, which is ugly, but works.

**Comment by pfn** [comment]
I would appreciate a PR that implements the workaround demonstrated in SI-7934
