### ISSUE TITLE
versionName = 0.1-SNAPSHOT in multiproject-lib-with-resources

### ISSUE THREAD

**Issue by Mygod** [scala-android/sbt-android#266]
I followed the example `multiproject-lib-with-resources` and the apk runs fine. The only problem is that `versionCode` is not set and `versionName` is set to `0.1-SNAPSHOT` in `AndroidManifest.xml` in the apk file. I have set valid `android:versionCode` and `android:versionName` in both `AndroidManifest.xml` files. I don't know what's wrong. Please assist.

Here's my `build.sbt`.

```
import android.Keys._

lazy val root = Project(id = "meta-project", base = file(".")).aggregate(mobile)

lazy val core = (project in file(".")).settings(android.Plugin.androidBuildAar).settings(commonSettings: _*).settings(
  exportJars := true,

  libraryDependencies ++= Seq(
    "com.j256.ormlite" % "ormlite-core" % "4.48",
    "com.j256.ormlite" % "ormlite-android" % "4.48"
  )
)

lazy val mobile = (project in file("mobile")).androidBuildWith(core).settings(commonSettings: _*).settings(
  name := "project-mobile",
  version := "2.10.3",
  libraryDependencies ++= Seq(
    "dnsjava" % "dnsjava" % "2.1.7",
    "com.github.kevinsawicki" % "http-request" % "6.0",
    "commons-net" % "commons-net" % "3.4",
    "eu.chainfire" % "libsuperuser" % "1.0.0.201602271131",
    "com.google.zxing" % "android-integration" % "3.2.1",
    "net.glxn.qrgen" % "android" % "2.0",
    "com.google.android.gms" % "play-services-base" % "8.4.0",
    "com.google.android.gms" % "play-services-ads" % "8.4.0",
    "com.google.android.gms" % "play-services-analytics" % "8.4.0",
    "com.android.support" % "design" % "23.3.0",
    "com.android.support" % "gridlayout-v7" % "23.3.0",
    "com.android.support" % "cardview-v7" % "23.3.0",
    "com.github.jorgecastilloprz" % "fabprogresscircle" % "1.01",
    "com.twofortyfouram" % "android-plugin-api-for-locale" % "1.0.2",
    "com.github.clans" % "fab" % "1.6.3"
  )
)

lazy val commonSettings = Seq(
  platformTarget in Android := "android-23",

  scalaVersion := "2.11.8",

  compileOrder in Compile := CompileOrder.JavaThenScala,

  javacOptions ++= Seq("-source", "1.6", "-target", "1.6"),

  scalacOptions ++= Seq("-target:jvm-1.6", "-Xexperimental"),

  ndkJavah in Android := List(),

  ndkBuild in Android := List(),

  shrinkResources in Android := true,

  typedResources in Android := false,

  resolvers += Resolver.jcenterRepo,

  resolvers += "JRAF" at "http://JRAF.org/static/maven/2"
)
```

Compiled with `sbt clean mobile/android:packageRelease`.

**Comment by pfn** [comment]
It is not possible for versionCode to be blank. It won't build and it won't
install. You need to be more specific.

**Comment by Mygod** [comment]
I decompiled AndroidManifest.xml with Root Explorer and didn't find versionCode. So I assume it's 0?

**Comment by Mygod** [comment]
Anyway the versionCode is malformed. I don't have 0.1-SNAPSHOT anywhere in my project. And it seems to be a default value of sbt project version.

**Comment by pfn** [comment]
It would be the default it is not set in xml

**Comment by Mygod** [comment]
But I've set `android:versionName` and `android:versionCode` both in `src/main/AndroidManifest.xml` and `mobile/src/main/AndroidManifest.xml`. :confused:

**Comment by pfn** [comment]
What you describe cannot possibly happen. Please provide a reproducible
repo.

https://github.com/scala-android/sbt-android/blob/master/src/rules.scala#L551

**Comment by Mygod** [comment]
It turned out `clean` didn't clean completely. It worked after I did a `mobile/clean` (I thought I've already tried that). Thanks.
