### ISSUE TITLE
Gradle version issue with sbt-android-gradle

### ISSUE THREAD

**Issue by sjrmanning** [scala-android/sbt-android#267]
I'm trying to use sbt-android-gradle on a project of mine, but it requires a later version of Gradle and unless I'm missing something, it seems like sbt-android-gradle is forcing Gradle 2.6.

```
[error] Gradle version 2.10 is required. Current version is 2.6. If using the gradle wrapper, try editing the distributionUrl in /Users/simon/.../gradle/wrapper/gradle-wrapper.properties to gradle-2.10-all.zip
[error] Failed to apply plugin [id 'com.android.library']
```

It's my first time giving this a go, so perhaps I've misconfigured something, but I can't see any reference to 2.6 in my project. Any ideas how I can get around this?

**Comment by pfn** [comment]
You need to change the gradle wrapper properties file to point to a newer
version of gradle, it is a properties file under the gradle/ directory in
your project.

**Comment by sjrmanning** [comment]
The weird thing is that my gradle wrapper properties file is pointing to a newer version — to `2.13` in fact. I think it's more likely an issue with my project configuration/layout.

**Comment by pfn** [comment]
sbt-android-gradle completely defers to the gradle wrapper to load and
import settings... Something else must be causing the version switch

**Comment by sjrmanning** [comment]
I think I've worked it out — had created the `plugins.sbt` file in the sub-project directory instead of at the top level where the root gradle build file is. My bad! The documentation does actually say where the correct place is :) Thanks for the quick response!
