### ISSUE TITLE
android:sourceDirectory points instrumentation test codes

### ISSUE THREAD

**Issue by illi-ichi** [scala-android/sbt-android#278]
After "gen-android", "show android:sourceDirectory" results "<base-dir>/src/androidTest", so apk contains binary for instrumentation test.

**Comment by pfn** [comment]
android:debugIncludesTests is true by default.

**Comment by illi-ichi** [comment]
Thank you for quick reply, and sorry for my misunderstanding.

Let me confirm:

- Any dependencies for instrumentation test should not be in test configuration.
- They should be always included in apk during debug, and will remove by proguard when release build.

**Comment by pfn** [comment]
Release build does not include tests, however, dependencies will not
necessarily be stripped (depends on static reachability)

**Comment by illi-ichi** [comment]
I understand. Thanks.

**Comment by pfn** [comment]
BTW, android:source* is instrumentation tests. It's not normal app, normal
sources are compile:source*

**Comment by illi-ichi** [comment]
Do you mean "android:run" is for normal app, and "android:test" is for instrumentation tests?

I confirmed that there are test classes in apk built by "android:run", and files under androidTest are observed during "~compile".

**Comment by pfn** [comment]
No,

debug/release are determined by `android:package-debug` and
`android:package-release`, all other tasks such as `android:package`,
`android:install`, `android:debug` and `android:run` take the last debug or
release state. The default is debug.
