### ISSUE TITLE
Generating dex step takes too long and crashes

### ISSUE THREAD

**Issue by kmisiunas** [scala-android/sbt-android#282]
I have to wait for very long time during step:

[info] Generating dex, incremental=false, multidex=false

and eventually it breaks with message:

```
UNEXPECTED TOP-LEVEL ERROR:
java.lang.OutOfMemoryError: GC overhead limit exceeded
com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: ForkOptions(None,Some(CustomOutput()),List(),None,Buffer(-Xmx1024m, -cp, /usr/local/opt/android-sdk/build-tools/23.0.3/lib/dx.jar),false,Map())
com.android.dx.command.Main --dex --num-threads=4 --output /Users/kmisiunas/Documents/Business/MC Sweeper/mc-sweeper/target/android/intermediates/dex 
...
```

However, if `sbt clean` is run beforehand the problem does not occur. This is rather new error and seems to have appeared after adding google services to the project. 

Full [error link](https://gist.github.com/kmisiunas/8936a34ddbf1b56e12ebf5c2c538be21) and [build.sbt link](https://gist.github.com/kmisiunas/87007ece87adee22d7c0975b8f9a10bd)

**Comment by pfn** [comment]
For general support, please use gitter
