### ISSUE TITLE
Make multi dex roots configurable as an option to avoid `Too many classes in --main-dex-list` for large multi-dex builds

### ISSUE THREAD

**Issue by svenwiegand** [scala-android/sbt-android#284]
For large builds, even multi dexing isn't enought -- instead it might happen, that we get the following error:

  `Too many classes in --main-dex-list, main dex capacity exceeded`

With the `dexMainClasses` you already provide an option to configure which classes to include in the main dex file, which is great, because a workaround for the problem is already available. Unfortunately at the moment I have no clue how to manually build this list.

In my previous gradle builds I've used the solution described in [Alex Lipov's blog post "Too many methods in main-dex?"](http://blog.osom.info/2014/12/too-many-methods-in-main-dex.html) which simply reduces the main dex roots (`dex.scala` line 278). 

E.g. for my app [uPod](https://play.google.com/store/apps/details?id=mobi.upod.app) I reduce the roots to `activity`, `service` and `provider` which works fine and reduces the resulting number of classes enough to prevent the `Too many classes in --main-dex-list` issue.

So if you would provide an option to make the main dex roots at `dex.scala` line 278 configurable it would be quite easy to solve this issue.

**Comment by pfn** [comment]
```
git clone https://github.com/scala-android/sbt-android
cd sbt-android
sbt publish-local
```

use `1.6.15-SNAPSHOT` until `1.6.15` is released sometime next week

**Comment by svenwiegand** [comment]
Man, that was freaking fast. Thanks a lot, will try this out.

Thanks for providing this great build system. It just took me a (quite long) evening to migrate the debug build of my large android app from gradle to sbt. Protify alone seems to be worth the effort.

Only thing that's missing currently is the release build. Need to find a way to make fabric.io crashlytics and beta work which I'm using in my gradle builds.

Will tell something about `sbt-android` in our German scala podcast [scalaprofis](http://scalaprofis.de).

**Comment by pfn** [comment]
Crashlytics needs something like

```
resValues += (("string", "com.crashlytics.android.build_id",
  java.util.UUID.randomUUID.toString))
```

Not sure about the rest of fabric.io

**Comment by seroperson** [comment]
@pfn u also need to inject api key into the manifest. 
for 'beta' support there is some additional .properties file must be packed along with apk
@svenwiegand try [this](https://github.com/seroperson/sbt-crashlytics)

**Comment by svenwiegand** [comment]
At first @pfn and @seroperson: Thanks a lot for your comments on this off-topic!

@pfn Further on the proguard mapping file needs to be uploaded somehow, because crashlytics also performs immediate deobfuscation if used correctly.

@seroperson Thanks for the hint to your plug-in -- will try it out today.

Also asked on [the fabric.io forum](https://twittercommunity.com/t/sbt-support/57556) (my comment there is still waiting for approval) for sbt-support and whether they're willing to provide information about their web API.
