### ISSUE TITLE
AbstractMethodError for AsyncTask

### ISSUE THREAD

**Issue by darkfrog26** [scala-android/sbt-android#285]
For some reason it would seem as though ProGuard isn't properly configured as I'm getting the following in my generated android app:

`Caused by: java.lang.AbstractMethodError: abstract method "java.lang.Object android.os.AsyncTask.doInBackground(java.lang.Object[])`

**Comment by pfn** [comment]
AsyncTask cannot be affected by proguard, another issue is at play.

Also, do not use AsyncTask, it is a mistake.

**Comment by darkfrog26** [comment]
Do you have a recommendation of what I should use instead?

**Comment by pfn** [comment]
A Future is an easy one

**Comment by darkfrog26** [comment]
Oh, I thought you couldn't use Futures on Android.  Thanks for the advice.

**Comment by Taig** [comment]
@darkfrog26 Futures work just fine. They work pretty well if you set up your `ExecutionContext`s properly: you could then replace your `runOnUiThread` calls with `myFuture.foreach( ... )( myUiThreadExecutionContext )`.

https://github.com/Taig/toolbelt/blob/1a8a450f5809b85bf9a7a5e6e5c829d10d3b721d/src/main/scala/io/taig/android/concurrent/Executor.scala
