### ISSUE TITLE
sbt hangs on resolving deprecated-use-gradle-api

### ISSUE THREAD

**Issue by maciek252** [scala-android/sbt-android#287]
There is no timeout, no error reported, sbt (0.13.12) simply hangs. It downloads some libraries before. The last message is:

Resolving com.android.tools.build#transform-api;2.0.0-deprecated-use-gradle-api

**Comment by pfn** [comment]
That would be an sbt bug

**Comment by maciek252** [comment]
I've tried with sbt 13.06, 13.08 and 13.10, still the same. Once I've got an error message after ~1 hour.

**Comment by pfn** [comment]
Sounds like you have a connectivity issue, and 0.13.6 is no longer
supported by sbt-android

**Comment by maciek252** [comment]
You are right, there was a connectivity problem. It's running when I connected using a mobile phone. I don't know why the faster cable connection failed, but it's easier to examine if the things work! Thanks.
