### ISSUE TITLE
`inflate` argument list should match the wrapped function

### ISSUE THREAD

**Issue by iphydf** [scala-android/sbt-android#290]
The TR version of `inflate` has shortened arguments:

``` scala
def inflate[A <: View](tl: TypedLayout[A], c: ViewGroup, b: Boolean): A = {
```

This makes it a little harder to migrate code from untyped inflate to typed inflate. More importantly though, there are coding guidelines requiring boolean arguments to be explicitly named, and `b` is not a very useful name, while `attachToRoot`, which is the original, is in fact useful.

**Comment by Taig** [comment]
I second that, annoys me every once in a while as well. But then again I never got around to create that trivial pull request. Maybe you could give it a try, @iphydf? :)
