### ISSUE TITLE
Any plan to support pseudoLocalesEnabled?

### ISSUE THREAD

**Issue by Mygod** [scala-android/sbt-android#291]
Note: Support for pseudoLocalesEnabled was added to the Gradle plugin version 0.14.2.

**Comment by pfn** [comment]
Submit a pr

**Comment by Mygod** [comment]
I'd love to but I'm not familiar with the Codebase yet. :/

**Comment by pfn** [comment]
Then probably not going to be supported without specific implementation
details

**Comment by Mygod** [comment]
It seems like they add a `strings.xml` for `en-XA` (perhaps another XB locale) and replace the characters if you have that enabled.

**Comment by pfn** [comment]
I have no idea what that means

**Comment by Mygod** [comment]
A quick Googling finds this: http://blog.danlew.net/2015/04/06/pseudolocalization-visiting-androids-bizarro-world/

**Comment by pfn** [comment]
I am not inclined to support this unless there is a professional need.

**Comment by pfn** [comment]
I guess it's a flag on aapt, easy enough, it'll go in 1.7.0
