### ISSUE TITLE
`clean` doesn't clean `$HOME/.android/sbt/exploded-aars/AAR-PACKAGE-FOLDER`

### ISSUE THREAD

**Issue by Mygod** [scala-android/sbt-android#295]
Maybe it's best to clean those folders too?

**Comment by pfn** [comment]
No, this is by design. Files unpacked there should never be modified.

1.7.3 will include a fix to unpack the aar again if files go missing.

**Comment by Mygod** [comment]
Sounds good!

**Comment by pfn** [comment]
f3ec083c8f154e046968caba663918e755eefcf8
