### ISSUE TITLE
在java中调用scala伴生对象 (java在项目的java目录中 scala在scala目录中 package一样)出现不能发现程序包

### ISSUE THREAD

**Issue by lovean** [scala-android/sbt-android#298]

**Comment by pfn** [comment]
Google Translated:
In java call scala associated objects (java in the project's java directory scala scala directory in the same package) can not find the package. 

No, this does not happen

**Comment by lovean** [comment]
@pfn hi
I created IndexActivity.java in the java folder of the project (package com.github.shadowsocks;) and wrote "ShadowsocksApplication $ .MODULE $ .app (). IsNatEnabled ();"
Scala directory has a ShadowsocksApplication.scala (package com.github.shadowsocks)
![5704c19c-2ade-4ce1-899c-792e3123dd26](https://cloud.githubusercontent.com/assets/16167147/22497289/97a0fc3c-e88b-11e6-8ba9-145e106406d6.png)
![46352a62-7437-4682-88e4-a63f7dfe7d95](https://cloud.githubusercontent.com/assets/16167147/22497288/97a0467a-e88b-11e6-91ff-56ee4178da02.png)
