### ISSUE TITLE
Java Call scala objects can not find the package

### ISSUE THREAD

**Issue by lovean** [scala-android/sbt-android#299]
I created IndexActivity.java in the java folder of the project (package com.github.shadowsocks;) and wrote "ShadowsocksApplication $ .MODULE $ .app (). IsNatEnabled ();"
Scala directory has a ShadowsocksApplication.scala (package com.github.shadowsocks)
![5704c19c-2ade-4ce1-899c-792e3123dd26](https://cloud.githubusercontent.com/assets/16167147/22497392/7055d278-e88c-11e6-881a-a396379db48a.png)
![46352a62-7437-4682-88e4-a63f7dfe7d95](https://cloud.githubusercontent.com/assets/16167147/22497393/705a3c64-e88c-11e6-81b0-5879a470566e.png)

**Comment by pfn** [comment]
Remove this line https://github.com/shadowsocks/shadowsocks-android/blob/master/build.sbt#L18
