### ISSUE TITLE
 javac returned nonzero exit code

### ISSUE THREAD

**Issue by FunnyDevs** [scala-android/sbt-android#302]
Hello! I have installed sbt-android from an existing gradle project, but i am not able to run the app because of this error, with no other message

[error] (app/compile:compileIncremental) javac returned nonzero exit code
[error] Total time: 23 s, completed 6-apr-2017 22.06.09

**Comment by pfn** [comment]
this is normally because of using java8 bytecode on a java7 vm or older.

**Comment by pfn** [comment]
er, actually, or trying to use java8 bytecode can also cause this, in a library can also cause this..., there's several reasons, actually... sadly, none of them give good information.

**Comment by FunnyDevs** [comment]
i Have java -version and javac- version pointing to the same java 8 sdk. So i think isn't a java 8 problem.

**Comment by pfn** [comment]
Run `last compile:compileIncremental` as indicated by the error. Take the
same javac flags and files listed, and run javac at the command line. This
will show you what the problem is
