### ISSUE TITLE
Fresco library is not visible

### ISSUE THREAD

**Issue by CodeCombiner** [scala-android/sbt-android#304]
Hi
 I have such interesting error, do you have any suggesitons?

`src/main/java/customviews/WrapContentDraweeView.java:15: object view is not a member of package com.facebook.drawee
[error] import com.facebook.drawee.view.SimpleDraweeView;`

<img width="412" alt="screen shot 2017-04-17 at 3 18 13 am" src="https://cloud.githubusercontent.com/assets/2519305/25075409/94f57b40-231c-11e7-8e13-65859e0dae9b.png">

<img width="830" alt="screen shot 2017-04-17 at 3 13 01 am" src="https://cloud.githubusercontent.com/assets/2519305/25075366/ce58ced8-231b-11e7-961b-0f792e6feefd.png">

build.sbt :

import com.android.tools.lint.checks.ApiDetector
import sbt.Keys._
import android.Keys.useProguardInDebug

enablePlugins(AndroidApp)

scalaVersion := "2.11.8"
javacOptions in Compile ++= "-source" :: "1.7" :: "-target" :: "1.7" :: Nil

platformTarget := "android-23"
proguardCache := Nil

resolvers in ThisBuild ++= Seq(
  Resolver.mavenLocal,
  Resolver.jcenterRepo,
  DefaultMavenRepository,
  Resolver.typesafeRepo("releases"),
  Resolver.typesafeRepo("snapshots"),
  Resolver.typesafeIvyRepo("snapshots"),
  Resolver.sonatypeRepo("releases"),
  Resolver.sonatypeRepo("snapshots"),
  Resolver.defaultLocal
)

resolvers += bintray.Opts.resolver.jcenter

lazy val androidScala = project
  .in(file("."))

  .settings(
    name := "android-scala",
    organization := "com.xxx",
    version := "0.0.1",
    platformTarget := "android-23",
    lintDetectors := Seq(ApiDetector.UNSUPPORTED),

    lintStrict := true,
    libraryDependencies ++= Seq(
	aar("com.google.android" % "multidex" % "0.1"),
      aar("com.android.support" % "support-v4" % "23.3.0"),
      aar("com.android.support" % "appcompat-v7" % "23.3.0"),
      "com.google.guava" % "guava" % "18.0",
      aar("com.android.support.test.espresso" % "espresso-idling-resource" % "2.2.2"),
      "com.squareup.retrofit2" % "retrofit" % "2.1.0",
                "com.squareup.retrofit2" %"converter-gson" % "2.1.0",
                    "commons-validator" % "commons-validator" % "1.6",
 aar("com.facebook.fresco" % "fresco" % "1.2.0"),
 aar("com.facebook.fresco" % "drawee" % "1.2.0"),
 aar("com.facebook.fresco" % "fbcore" % "1.2.0"),
 aar("com.facebook.fresco" % "imagepipeline-base" % "1.2.0"),
 aar("com.facebook.fresco" % "imagepipeline" % "1.2.0"),
 aar("com.facebook.fresco" % "animated-gif" % "1.2.0"),
 aar("com.facebook.fresco" % "imagepipeline-okhttp" % "1.2.0"),
 aar("com.facebook.fresco" % "animated-base" % "1.2.0"),
 aar("com.facebook.fresco" % "webpsupport" % "1.2.0")
     )			
  )

transitiveAndroidLibs in Android := false

packagingOptions in Android := PackagingOptions(excludes = Seq(
  "META-INF/MANIFEST.MF",
  "META-INF/LICENSE.txt",
  "META-INF/LICENSE",
  "META-INF/NOTICE.txt",
  "META-INF/NOTICE"
))

useProguard in Android := false

useProguardInDebug in Android := false

proguardScala in Android := false

dexMulti in Android := true
   transitiveAndroidLibs in Android := false
dexMinimizeMain in Android := false

dexMaxProcessCount := 1

dexMainClasses in Android := Seq(
  
  "android/support/multidex/BuildConfig.class",
  "android/support/multidex/MultiDex$V14.class",
  "android/support/multidex/MultiDex$V19.class",
  "android/support/multidex/MultiDex$V4.class",
  "android/support/multidex/MultiDex.class",
  "android/support/multidex/MultiDexApplication.class",
  "android/support/multidex/MultiDexExtractor$1.class",
  "android/support/multidex/MultiDexExtractor.class",
  "android/support/multidex/ZipUtil$CentralDirectory.class",
  "android/support/multidex/ZipUtil.class"
)

showSdkProgress in Android := false
fork in Test := true

**Comment by pfn** [comment]
If it builds from sbt then it is an ide configuration issue. Add the
requisite jar to the ide project

**Comment by CodeCombiner** [comment]
Unfortunately sbt shows same error
<img width="415" alt="screen shot 2017-04-17 at 3 39 30 am" src="https://cloud.githubusercontent.com/assets/2519305/25075537/900a6b56-231f-11e7-8d0c-6331f6f91401.png">

**Comment by pfn** [comment]
Then you're missing the library in your dependencies

**Comment by pfn** [comment]
It's also possible that somehow the contents of the aar were corrupted. It should automatically fix itself, but if you're running an old version of sbt-android it won't. In that case `rm -r ~/. android/sbt/exploded-aars`

**Comment by pfn** [comment]
You also set transitiveAndroidLibs to false, this can also cause problems if you're doing it for the wrong reasons

**Comment by CodeCombiner** [comment]
I have also tried to clean .ivy2 and this did not help. It seems it is library issue. For example I had the same issue with support 23.0.1 libraries but not with 23.3.0. I tried to change Fresco versions - this did not help. So I have to use Picasso library now :(

**Comment by pfn** [comment]
cannot reproduce, remove transitiveAndroidLibs as previously mentioned.
