### ISSUE TITLE
Is typedResources still useful?

### ISSUE THREAD

**Issue by Mygod** [scala-android/sbt-android#305]
In O preview, `findViewById` no longer requires type cast.

**Comment by pfn** [comment]
Please provide details

**Comment by Mygod** [comment]
Never mind. It seems that this change only affects `View` but not other classes.

**Comment by Mygod** [comment]
Wait. It seems in O preview 2 every other `findViewById` changed too.

What I meant is that the current signature for `findViewById` is like this:

```
public <T extends View> T findViewById(int id);
```

**Comment by pfn** [comment]
Indeed, that removes the need for explicit casting, but an unsafe cast will still occur when doing that.

**Comment by Mygod** [comment]
How does TR handle it if two conflicting types of View has the same ID?

**Comment by pfn** [comment]
Nearest common parent in framework (cannot find common parents in local
code).
