### ISSUE TITLE
Packaged native libraries not included in APK

### ISSUE THREAD

**Issue by ajaychandran** [scala-android/sbt-android#310]
[LibGdx](https://github.com/libgdx/libgdx/) publishes native libraries in JAR files. When added as a dependency, the packaged **.so** file is not included in the APK built.

#### Dependency
```sbt
"com.badlogicgames.gdx" % "gdx-platform" % "1.9.6" classifier "natives-armeabi-v7a"
```
#### Note
The native library, **libgdx.so**, is included in **classes.proguard.jar**.
Tested with **sbt-android 1.7.7**.

**Comment by pfn** [comment]
The library must be packaged with the correct abi path. This is not an
issue.

**Comment by ajaychandran** [comment]
Thanks, you just saved my day!

For LibGdx users, the native libraries should be extracted to **src/main/libs/[abi]/**.
Also, use ProGuard settings found [here](https://stackoverflow.com/questions/18288856/proguard-and-libgdx-runtimeexception).
