### ISSUE TITLE
Add support for Annotation Processors

### ISSUE THREAD

**Issue by Empty2k12** [scala-android/sbt-android#313]
Starting with version 2.3.0 the Android Gradle Plugin has built-in support for treating dependencies as annotation processors.

```
dependencies {
    annotationProcessor "org.androidannotations:androidannotations:1.1.0"
    compile "org.androidannotations:androidannotations-api:1.1.0"
}
```

**Comment by pfn** [comment]
You can add dependencies as "provided" or "compile-internal" to be
annotation processors

**Comment by Empty2k12** [comment]
We have been using it in conjunction with the Glide image loading library and it's preprocessor. 

Adding the annotation processor dependency as "compile", "compile-internal" or "provided" all did not fix our issue.

> Failed to find GeneratedAppGlideModule. You should include an annotationProcessor compile dependency on com.github.bumptech.glide:glide:compiler in your application and a @GlideModule annotated AppGlideModule implementation or LibraryGlideModules will be silently ignored

**Comment by pfn** [comment]
java annotation processors only work on java code. they only run during javac phase. If they're bytecode processing annotations, you can do it as a post-processing step against compiled scala code, a la https://github.com/gregghz/sbt-android-room

**Comment by Empty2k12** [comment]
Thank you for your fast replies, I guess we will roll with the warning then. Keep up the good work
