### ISSUE TITLE
@ViewLayoutId(R.layout.main) 编译问题

### ISSUE THREAD

**Issue by WeiChou** [scala-android/sbt-android#321]
我遇到了一个编译错误：

> .../MainActy.scala:9: annotation argument needs to be a constant; found: R.layout.main
[error] @ViewLayoutId(R.layout.main)
[error]                        ^
[error] one error found

当我编译代码的时候：

>@ViewLayoutId(R.layout.main)
class MainActy extends Activity with TypedFindView with AssoidCompat {

但是，它的确是 `final` 的：

>R.java
public static final int main=0x7f03001b;

这个问题怎么破。

**Comment by pfn** [comment]
You're looking at the wrong R.java

This is caused by using a library project.

Not a bug
