### ISSUE TITLE
Android O and android.support.v7.app.AppCompatActivity compatibility for TypedFindView#findViewById

### ISSUE THREAD

**Issue by chenakam** [scala-android/sbt-android#324]
When use Android O Sdk:
`platformTarget in Android := "android-26"`,
the generated `TypedFindView#findViewById` method signature is as follows:
```
trait TypedFindView extends Any {
  protected def findViewById[V <: View](id: Int): V
  ...
}
```
it compat with `android.app.Activity#findViewById`, but not compat with `android.support.v7.app.AppCompatActivity#findViewById`:
```
public View findViewById(@IdRes int id) { return this.getDelegate().findViewById(id); }
```
i means we can fix this problem as follows:
```
class Compat4ActyV7 extends AppCompatActivity with TypedFindView {
  protected def findViewById[V <: View](id: Int)(implicit v: V = null): V = super[AppCompatActivity].findViewById(id).asInstanceOf[V]
}
```

**Comment by Taig** [comment]
You have to update your support library to 26+:
```
public <T extends View> T findViewById(@IdRes int id)
```

**Comment by chenakam** [comment]
i have already setting up `libraryDependencies += "com.android.support" % "appcompat-v7" % "26.+"`, but... 
and there is no harm in choosing one more choice.

**Comment by pfn** [comment]
the correct choice is to use the corresponding support library for the platform.
