### ISSUE TITLE
TypedFindView.findView raise compiling error

### ISSUE THREAD

**Issue by vberezkin** [scala-android/sbt-android#326]
There is an error **TR.scala: dead code following this construct final def findView[A](tr: TypedResource[A]): A = findViewById(tr.id).asInstanceOf[A]** if I compile with targetSdkVersion=27 and "warn-dead-code" option turned on.

**Comment by pfn** [comment]
Is platformTarget set to android-27?

**Comment by vberezkin** [comment]
Yes,
```
  minSdkVersion := "16",
  targetSdkVersion := "27",
  platformTarget := "android-27",
  buildToolsVersion := Some("27.0.2"),

```
