### ISSUE TITLE
unable to get resource for com.hanhuy.sbt#android-sdk-plugin;1.5.19

### ISSUE THREAD

**Issue by pzl237** [scala-android/sbt-android#328]
in plugins.sbt, I add this line: 
addSbtPlugin("com.hanhuy.sbt" % "android-sdk-plugin" % "1.5.19")

when I run "sbt clean android:package-release"，
error info:
[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.hanhuy.sbt#android-sdk-plugin;1.5.19: typesafe-ivy-releases: unable to get resource for com.hanhuy.sbt#android-sdk-plugin;1.5.19: res=https://repo.typesafe.com/typesafe/ivy-releases/com.hanhuy.sbt/android-sdk-plugin/scala_2.12/sbt_1.0/1.5.19/ivys/ivy.xml: java.net.ConnectException: Failed to connect to repo.typesafe.com/34.227.246.125:443

**Comment by pfn** [comment]
Must use sbt 0.13.x atm

**Comment by pzl237** [comment]
ok, I try use sbt 0.13.15, and can compile successfully. Thank you！
