### ISSUE TITLE
Quickstart Does Not Work

### ISSUE THREAD

**Issue by R030t1** [scala-android/sbt-android#330]
When following the steps at http://scala-android.org/quickstart/, running `sbt` informs me that `org.scala-android` can't be found. No solutions are forthcoming, I had to instead look at Scaloid.

**Comment by pfn** [comment]
Sbt 0.13.16 is required.

**Comment by R030t1** [comment]
The project does not work with the latest sbt and is out of date? Why was this issue closed? Should I make another?

When I ran sbt the first time it downloaded version 0.13.16 of itself, but I still am unable to build the project.

**Comment by pfn** [comment]
The quick start is correct with exception of omission of setting sbt version. That has been updated. If you are looking for support, consider using the gitter or other avenues.
