### ISSUE TITLE
sbt 0.13.15. Not found repository "org.scala-android" % "sbt-android

### ISSUE THREAD

**Issue by juankr10s** [scala-android/sbt-android#333]
i´m using "addSbtPlugin("org.scala-android" % "sbt-android" % "1.7.7")" but don't work. 

any suggestion?

**Comment by pfn** [comment]
should work fine, try again.

**Comment by juankr10s** [comment]
hi,
yesterday it worked well
now error:

[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.hanhuy.sbt#android-sdk-plugin;1.6.0: not found
[warn]  :: com.github.mpeltonen#sbt-idea;1.7.0-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::

[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.hanhuy.sbt#android-sdk-plugin;1.6.0: not found
[error] unresolved dependency: com.github.mpeltonen#sbt-idea;1.7.0-SNAPSHOT: not found

I have tried with 1.3.5 but again error:
[warn]            +- default:lcamera_5-build:0.1.0-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.hanhuy.sbt#android-sdk-plugin;1.3.5: not found
[error] unresolved dependency: com.github.mpeltonen#sbt-idea;1.7.0-SNAPSHOT: not found

the beste regards Juan Carlos

**Comment by pfn** [comment]
Sounds like you're using the wrong coordinates.

Should be something like
org.scala-android sbt-android ...
