### ISSUE TITLE
Resources will not get copied into the final apk from sbt project dependencies

### ISSUE THREAD

**Issue by qwe2** [scala-android/sbt-android#46]
This is connected to my previous problem. Earlier I was pulling my own dependencies from local repository with sbt's `publish-local` and defining them as `libraryDependencies` and it did work fine. For convenience I wanted to define my own project as ProjectRef in my android build and the `exportJars` setting did indeed fix the problem but now the resources from the root of the dependency jar files won't get copied into the built apk file while they were working fine when I was using local repository. They are there in the classes.proguard.jar but they obviously don't get dexed but won't be put into the apk either causing runtime error when I try to load them.

**Comment by pligor** [comment]
Hi,

I&#39;d like to add you to my professional network on LinkedIn.

- George

Accept: https://www.linkedin.com/blink?simpleRedirect=0OejkOdzgSdj4VdzwNe34UdPARfkh9rCZFt65QqnpKqipFjBZQcnF5ljRVpkJApn9xq7cCt7dBtmtvpnhFtCVFfmJB9C5QoORBt6BSrCAJt7dBtmsJr6RBfmtKqmJzon9Q9ClQqnpKimtBkClOs3Rx9C8PbnAMumEMsPpFbj9RoztIu3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5978181886919352320_500&markAsRead=


You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=ozcJuj1Vqz1PdCAJcDlydSNUfmhFpip1nSBid71qjA9KrCpJgnoUkDlooB1Wiltvr7hFgzoSdC5jdQJ1s3d7cRhbdPlLlAoUs4JFclh8p7xyrQxdjDxCe6hJr71NlSFkejhVk3xisAMRhDBkhQJ8mCsMmmAOtTx1glF6clpomkd8kjdarTpVhAdphCtFiBBokCoNcjsQdklynRZFtSxHdmhmsBgOhm9Slk51gnt7ejxBsQNyjSxghl51fmhFrSMCt7dBtmtvpnhFtCVFfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9C8PbnAMumEMsPpFbj9RoztIu3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5978181886919352320_500&amp;markAsRead= Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=e3wTd3RAimlIoSBQsC4Ct7dBtmtvpnhFtCVFfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9C8PbnAMumEMsPpFbj9RoztIu3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5978181886919352320_500&markAsRead=
&copy; 2014, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by pligor** [comment]
LinkedIn
------------

You've joined the world's largest professional network. Here's how to get started.

George Pligoropoulos,
Welcome to the world's largest professional network.

Get started: www.linkedin.com/nhome/get-started

---

Stay connected
See which of the 260+ million LinkedIn professionals you already know: www.linkedin.com/fetch/importAndInviteEntry

Be discovered
Tell your professional story and be found for career opportunities: https://www.linkedin.com/profile/edit

Get inspired
Follow LinkedIn Influencers to get unique insights from industry leaders: www.linkedin.com/today/influencers

Thanks for joining!
The LinkedIn Team

**Comment by pligor** [comment]
George Pligoropoulos, LinkedIn is better with connections!
See what your colleagues and classmates have been up to. Add them as connections.

Jaffer Ali
CAFM Consultant & Oracle DBA & Technical Support Engineer at MBUZZ Technology
Connect https://www.linkedin.com/e/v2?e=6q9z8z-i6xlo9wt-1v&amp;t=int&amp;midToken=AQF6x8ZFEvSlLA&amp;tracking=&amp;ek=welcome_pymk_v2&amp;firstName=Jaffer&amp;lastName=Ali&amp;from=email&amp;ID=381625580&amp;authType=name&amp;_sig=2qLqXTp-umzSE1

Previewict/Dealer-Po Rahul
--
Connect https://www.linkedin.com/e/v2?e=6q9z8z-i6xlo9wt-1v&amp;t=int&amp;midToken=AQF6x8ZFEvSlLA&amp;tracking=&amp;ek=welcome_pymk_v2&amp;firstName=Previewict%2FDealer-Po&amp;lastName=Rahul&amp;from=email&amp;ID=367414970&amp;authType=name&amp;_sig=22jOpcrFamzSE1

chung yan cheng
Senior Electronics Engineer at Amonics Limited
Connect https://www.linkedin.com/e/v2?e=6q9z8z-i6xlo9wt-1v&amp;t=int&amp;midToken=AQF6x8ZFEvSlLA&amp;tracking=&amp;ek=welcome_pymk_v2&amp;firstName=chung+yan&amp;lastName=cheng&amp;from=email&amp;ID=145789126&amp;authType=name&amp;_sig=3JIe3JnHemzSE1

Mher Mangasaryan
Phonegap
Connect https://www.linkedin.com/e/v2?e=6q9z8z-i6xlo9wt-1v&amp;t=int&amp;midToken=AQF6x8ZFEvSlLA&amp;tracking=&amp;ek=welcome_pymk_v2&amp;firstName=Mher&amp;lastName=Mangasaryan&amp;from=email&amp;ID=50787353&amp;authType=name&amp;_sig=2_CjpfRUCmzSE1



This email was intended for George Pligoropoulos is an idiot spammer. (Spamcop at Spamcop). 
Learn why we included this: https://www.linkedin.com/e/v2?e=6q9z8z-i6xlo9wt-1v&amp;a=customerServiceUrl&amp;midToken=AQF6x8ZFEvSlLA&amp;ek=welcome_pymk_v2&amp;articleId=4788

&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by pligor** [comment]
Adding your experiences to your profile helps you get found for more opportunities.

George Pligoropoulos,
Spamcop at Spamcop


Current:Spamcop at Spamcop
Past:https://www.linkedin.com/e/v2?e=6q9z8z-i73bzhwy-1f&t=nge&midToken=AQF6x8ZFEvSlLA&tracking=eml-cmktg-welc_prof-past_pos&ek=welcome_profile_edit&startTask=ADD_POSITION&force=true
Education:https://www.linkedin.com/e/v2?e=6q9z8z-i73bzhwy-1f&t=nge&midToken=AQF6x8ZFEvSlLA&tracking=eml-cmktg-welc_prof-edu&ek=welcome_profile_edit&startTask=SCHOOL_NAME&force=true

Add your experience https://www.linkedin.com/e/v2?e=6q9z8z-i73bzhwy-1f&t=nge&midToken=AQF6x8ZFEvSlLA&tracking=eml-cmktg-welc_prof-btn&ek=welcome_profile_edit&force=true

This email was intended for George Pligoropoulos is an idiot spammer. (Spamcop at Spamcop). 
Learn why we included this: https://www.linkedin.com/e/v2?e=6q9z8z-i73bzhwy-1f&amp;a=customerServiceUrl&amp;midToken=AQF6x8ZFEvSlLA&amp;ek=welcome_profile_edit&amp;articleId=4788

&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by pligor** [comment]
Please view this email in a browser: 
https://e.linkedin.com/pub/sf/FormLink?_ri_=X0Gzc2X%3DWQpglLjHJlYQGlyR2zbRT1jksHLlzfXKSzfYOhWRP8DJlaEw82BEc5VXMtX%3DWQpglLjHJlYQGlJzen1wAmGcmrOgonzf4PGyozbdRk0kEzeupDryjbR&_ei_=ErFih1Re-HqyS2rX01bUHprOzuZfniTKlmrjd-rwe0tQdxSgbjSDfq8lChA89ythEEGsYcuwyRg.Jg%3D%3D

If you prefer not to receive these messages: 
https://e.linkedin.com/pub/cc?_ri_=X0Gzc2X%3DWQpglLjHJlYQGlyR2zbRT1jksHLlzfXKSzfYOhWRP8DJlaEw82BEc5VXtpKX%3DUSDTDY&_ei_=ErFih1Re-HqyS2rX01bUHprfLDdm08Bcj5cE2fgqvgNkCX1arB37505XpduO0pIrgCf7r70advWBeK1SP0pqimIfjgkyzu1u-L59RuNvjSJNhLM2k9sVR9_aKGVwJ2ccAQjqHanFQoFa3wKhfyVBf4NuOIL0S9FfRyqRHo4zhUj4ix8puAgLzprrEXTxo6aETCFfN982bK_fKsJ0PidBVpY1bziac30o8AptEOCw0KqSJFNt_FDbgZgDTRVdnMsZ_oxB3HYCkkw2dQkRa6VfCnZ_ZMORIu_fVzV4TUp_Xint_rUF5uU11R1gHXX40rw5DZVPu-XuDyStBLajvSq8hrsKShNM-xEvjyvPT3X86giHBkzKDB8.Jg%3D%3D

If you need assistance or have questions, please contact LinkedIn Customer Service: 
https://e.linkedin.com/pub/cc?_ri_=X0Gzc2X%3DWQpglLjHJlYQGlyR2zbRT1jksHLlzfXKSzfYOhWRP8DJlaEw82BEc5VXtpKX%3DUSDUUY&_ei_=ErFih1Re-HqyS2rX01bUHprfLDdm08Bcj5cE2fgqvgNkCX1arB37505XpduO0pIrgCf7r70advWBeK1SP0pqimIfjgkyzu1u-L59RuNvjSJNhLM2k9sVR9_aKGVwJ2ccAXe2XTxJaBT5CikYUs0-d414SGOBWt6aiwU.Jg%3D%3D

This email was intended for George Pligoropoulos is an idiot spammer. (Spamcop at Spamcop). Learn how this information helps us protect your security: 
https://e.linkedin.com/pub/cc?_ri_=X0Gzc2X%3DWQpglLjHJlYQGlyR2zbRT1jksHLlzfXKSzfYOhWRP8DJlaEw82BEc5VXtpKX%3DUSDUYY&_ei_=ErFih1Re-HqyS2rX01bUHprfLDdm08Bcj5cE2fgqvgNkCX1arB37505XpduO0pIrgCf7r70advWBeK1SP0pqimIfjgkyzu1u-L59RuNvjSJNhLM2k9sVR9_aKGVwJ2ccAXe2XTxJaBT5CikYUs0-d414SGOBWt6aiwU.Jg%3D%3D

LinkedIn Corporation. 2029 Stierlin Ct, Mountain View, CA 94043, USA.
.

**Comment by pligor** [comment]
Dear George Pligoropoulos,

See who from your contacts you already know on LinkedIn. Now it's easy to connect with people you email.

Continue: https://www.linkedin.com/e/v2?e=6q9z8z-i7da8bn7-50&amp;t=fiie&amp;midToken=AQF6x8ZFEvSlLA&amp;tracking=eml-cmktg-welc_abook_std-btn&amp;ek=welcome_abook

This email was intended for George Pligoropoulos is an idiot spammer. (Spamcop at Spamcop). 
Learn why we included this: https://www.linkedin.com/e/v2?e=6q9z8z-i7da8bn7-50&amp;a=customerServiceUrl&amp;midToken=AQF6x8ZFEvSlLA&amp;ek=welcome_abook&amp;articleId=4788

&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA
