### ISSUE TITLE
Consider making check for ANDROID_HOME a warning instead of an error

### ISSUE THREAD

**Issue by aginiewicz** [scala-android/sbt-android#90]
Would it be possible to make check for ANDROID_HOME a warning instead of an error - and fail only when someone actually uses some Android related commands like android:package-debug?

I ask because I work on cross-platform application - we use Libgdx and build for Desktop, Android and iOS using same source and very thin layer (like few classes) of platform dependent code. Unfortunately, putting android-sdk-plugin in forces everyone to have Android SDK installed - even if they only want to build iOS or Desktop version. This was a big complain from people who make our iOS and Mac builds.

We mostly use libgdx-sbt-project.g8 template and the issue is tracked there as well: https://github.com/ajhager/libgdx-sbt-project.g8/issues/65 (it dated back to when libgdx-sbt-project.g8 used another Android plugin - and this idea is duplicated there as https://github.com/jberkel/android-plugin/issues/199).

Anyway, thanks for great plugin! It really helps us in getting things done!

**Comment by pfn** [comment]
this has probably been made worse by recent changes, all of the android SDK stuff is now loaded eagerly

**Comment by pfn** [comment]
a fallback value will be used if ANDROID_HOME is not set. If android packages are not present when the build is run, they will be auto-installed.

As long as android tasks are not executed, nothing will get installed to the fallback directory.
