### ISSUE TITLE
Dynamically modifying the manifest

### ISSUE THREAD

**Issue by bertvh** [scala-android/sbt-android#95]
In order to make different builds for our testing an production environment, I want to change for example the app label during the build. I tried to do this by modifying the android:manifest setting.

Before modification

```
show android:manifest
   <application ... android:label="myapp">....</application>
```

After modification

```
show android:manifest
    <application ... android:label="myapp-testenv">....</application>
```

Manifest-wise, this is what I want. However, the application that gets build still has the label of the unmodified manifest.

Am I doing this wrong or is this a bug?

**Comment by pfn** [comment]
This is somewhat verbose, but I ran into a similar situation for a custom attribute recently, and I can't use manifest-placeholders because the primary build is in gradle/maven:

```scala
val processManifest = TaskKey[File]("process-manifest")
processManifest in Android <<= (processManifest in Android) map { manifest =>
  import scala.xml._
  val root = XML.loadFile(manifest)
  def updateVmSafeMode(node: Node): Node = {
    def updateNodes(ns: Seq[Node], mayChange: Boolean): Seq[Node] =
      for(subnode <- ns) yield subnode match {
        case Elem(prefix, "application", attribs, scope, children @ _*) if mayChange =>
          Elem(prefix, "application", new PrefixedAttribute("android", "vmSafeMode", "true", attribs),
            scope, true, children:_*)
        case Elem(prefix, "manifest", attribs, scope, children @ _*) =>
          Elem(prefix, "manifest", attribs, scope, true, updateNodes(children, true) : _*)
        case Elem(prefix, label, attribs, scope, children @ _*) =>
          Elem(prefix, label, attribs, scope, true, updateNodes(children, false) : _*)
        case other => other  // preserve text
      }

    updateNodes(node.theSeq, false).head
  }
  XML.save(manifest.getAbsolutePath, updateVmSafeMode(root))
  manifest
}
```

**Comment by vivekshinde099** [comment]
if you want to create build-wise environment like(Test, Build, Release)  then why don't you use flavoring concept in android
Refer below link : 
https://medium.com/simform-engineering/basic-use-of-android-product-flavors-build-variants-315a4e11e435

hope this will help you....
